/*
 * Copyright (c) 2024. Marcel van Heerwaarden
 *
 * Copyright (C) 2019 The Android Open Source Project
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.mheerwaarden.dynamictheme.ui

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.saveable.Saver
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import dynamiccolor.DynamicScheme

data class ColorSchemeState(
    val primary: Int = 0,
    val onPrimary: Int = 0,
    val primaryContainer: Int = 0,
    val onPrimaryContainer: Int = 0,
    val inversePrimary: Int = 0,
    val secondary: Int = 0,
    val onSecondary: Int = 0,
    val secondaryContainer: Int = 0,
    val onSecondaryContainer: Int = 0,
    val tertiary: Int = 0,
    val onTertiary: Int = 0,
    val tertiaryContainer: Int = 0,
    val onTertiaryContainer: Int = 0,
    val background: Int = 0,
    val onBackground: Int = 0,
    val surface: Int = 0,
    val onSurface: Int = 0,
    val surfaceVariant: Int = 0,
    val onSurfaceVariant: Int = 0,
    val surfaceTint: Int = 0,
    val inverseSurface: Int = 0,
    val inverseOnSurface: Int = 0,
    val error: Int = 0,
    val onError: Int = 0,
    val errorContainer: Int = 0,
    val onErrorContainer: Int = 0,
    val outline: Int = 0,
    val outlineVariant: Int = 0,
    val scrim: Int = 0,
    val surfaceBright: Int = 0,
    val surfaceContainer: Int = 0,
    val surfaceContainerHigh: Int = 0,
    val surfaceContainerHighest: Int = 0,
    val surfaceContainerLow: Int = 0,
    val surfaceContainerLowest: Int = 0,
    val surfaceDim: Int = 0,
)

// Create a custom Saver for ColorSchemeState
val ColorSchemeStateSaver: Saver<ColorSchemeState, *> = Saver(
    save = { colorSchemeState ->
        listOf(
            colorSchemeState.primary,
            colorSchemeState.onPrimary,
            colorSchemeState.primaryContainer,
            colorSchemeState.onPrimaryContainer,
            colorSchemeState.inversePrimary,
            colorSchemeState.secondary,
            colorSchemeState.onSecondary,
            colorSchemeState.secondaryContainer,
            colorSchemeState.onSecondaryContainer,
            colorSchemeState.tertiary,
            colorSchemeState.onTertiary,
            colorSchemeState.tertiaryContainer,
            colorSchemeState.onTertiaryContainer,
            colorSchemeState.background,
            colorSchemeState.onBackground,
            colorSchemeState.surface,
            colorSchemeState.onSurface,
            colorSchemeState.surfaceVariant,
            colorSchemeState.onSurfaceVariant,
            colorSchemeState.surfaceTint,
            colorSchemeState.inverseSurface,
            colorSchemeState.inverseOnSurface,
            colorSchemeState.error,
            colorSchemeState.onError,
            colorSchemeState.errorContainer,
            colorSchemeState.onErrorContainer,
            colorSchemeState.outline,
            colorSchemeState.outlineVariant,
            colorSchemeState.scrim,
            colorSchemeState.surfaceBright,
            colorSchemeState.surfaceContainer,
            colorSchemeState.surfaceContainerHigh,
            colorSchemeState.surfaceContainerHighest,
            colorSchemeState.surfaceContainerLow,
            colorSchemeState.surfaceContainerLowest,
            colorSchemeState.surfaceDim,
        )
    },
    restore = { list ->
        ColorSchemeState(
            primary = list[0],
            onPrimary = list[1],
            primaryContainer = list[2],
            onPrimaryContainer = list[3],
            inversePrimary = list[4],
            secondary = list[5],
            onSecondary = list[6],
            secondaryContainer = list[7],
            onSecondaryContainer = list[8],
            tertiary = list[9],
            onTertiary = list[10],
            tertiaryContainer = list[11],
            onTertiaryContainer = list[12],
            background = list[13],
            onBackground = list[14],
            surface = list[15],
            onSurface = list[16],
            surfaceVariant = list[17],
            onSurfaceVariant = list[18],
            surfaceTint = list[19],
            inverseSurface = list[20],
            inverseOnSurface = list[21],
            error = list[22],
            onError = list[23],
            errorContainer = list[24],
            onErrorContainer = list[25],
            outline = list[26],
            outlineVariant = list[27],
            scrim = list[28],
            surfaceBright = list[29],
            surfaceContainer = list[30],
            surfaceContainerHigh = list[31],
            surfaceContainerHighest = list[32],
            surfaceContainerLow = list[33],
            surfaceContainerLowest = list[34],
            surfaceDim = list[35],
        )
    }
)

fun DynamicScheme.toColorSchemeState(): ColorSchemeState =
        ColorSchemeState(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            inversePrimary = inversePrimary,
            secondary = secondary,
            onSecondary = onSecondary,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onSecondaryContainer,
            tertiary = tertiary,
            onTertiary = onTertiary,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onTertiaryContainer,
            background = background,
            onBackground = onBackground,
            surface = surface,
            onSurface = onSurface,
            surfaceVariant = surfaceVariant,
            onSurfaceVariant = onSurfaceVariant,
            surfaceTint = surfaceTint,
            inverseSurface = inverseSurface,
            inverseOnSurface = inverseOnSurface,
            error = error,
            onError = onError,
            errorContainer = errorContainer,
            onErrorContainer = onErrorContainer,
            outline = outline,
            outlineVariant = outlineVariant,
            scrim = scrim,
            surfaceBright = surfaceBright,
            surfaceContainer = surfaceContainer,
            surfaceContainerHigh = surfaceContainerHigh,
            surfaceContainerHighest = surfaceContainerHighest,
            surfaceContainerLow = surfaceContainerLow,
            surfaceContainerLowest = surfaceContainerLowest,
            surfaceDim = surfaceDim,
        )

fun fromColorSchemeState(colorSchemeState: ColorSchemeState): ColorScheme =
        ColorScheme(
            primary = Color(colorSchemeState.primary),
            onPrimary = Color(colorSchemeState.onPrimary),
            primaryContainer = Color(colorSchemeState.primaryContainer),
            onPrimaryContainer = Color(colorSchemeState.onPrimaryContainer),
            inversePrimary = Color(colorSchemeState.inversePrimary),
            secondary = Color(colorSchemeState.secondary),
            onSecondary = Color(colorSchemeState.onSecondary),
            secondaryContainer = Color(colorSchemeState.secondaryContainer),
            onSecondaryContainer = Color(colorSchemeState.onSecondaryContainer),
            tertiary = Color(colorSchemeState.tertiary),
            onTertiary = Color(colorSchemeState.onTertiary),
            tertiaryContainer = Color(colorSchemeState.tertiaryContainer),
            onTertiaryContainer = Color(colorSchemeState.onTertiaryContainer),
            background = Color(colorSchemeState.background),
            onBackground = Color(colorSchemeState.onBackground),
            surface = Color(colorSchemeState.surface),
            onSurface = Color(colorSchemeState.onSurface),
            surfaceVariant = Color(colorSchemeState.surfaceVariant),
            onSurfaceVariant = Color(colorSchemeState.onSurfaceVariant),
            surfaceTint = Color(colorSchemeState.surfaceTint),
            inverseSurface = Color(colorSchemeState.inverseSurface),
            inverseOnSurface = Color(colorSchemeState.inverseOnSurface),
            error = Color(colorSchemeState.error),
            onError = Color(colorSchemeState.onError),
            errorContainer = Color(colorSchemeState.errorContainer),
            onErrorContainer = Color(colorSchemeState.onErrorContainer),
            outline = Color(colorSchemeState.outline),
            outlineVariant = Color(colorSchemeState.outlineVariant),
            scrim = Color(colorSchemeState.scrim),
            surfaceBright = Color(colorSchemeState.surfaceBright),
            surfaceContainer = Color(colorSchemeState.surfaceContainer),
            surfaceContainerHigh = Color(colorSchemeState.surfaceContainerHigh),
            surfaceContainerHighest = Color(colorSchemeState.surfaceContainerHighest),
            surfaceContainerLow = Color(colorSchemeState.surfaceContainerLow),
            surfaceContainerLowest = Color(colorSchemeState.surfaceContainerLowest),
            surfaceDim = Color(colorSchemeState.surfaceDim),
        )

fun ColorScheme.toColorSchemeState(): ColorSchemeState =
        ColorSchemeState(
            primary = primary.toArgb(),
            onPrimary = onPrimary.toArgb(),
            primaryContainer = primaryContainer.toArgb(),
            onPrimaryContainer = onPrimaryContainer.toArgb(),
            inversePrimary = inversePrimary.toArgb(),
            secondary = secondary.toArgb(),
            onSecondary = onSecondary.toArgb(),
            secondaryContainer = secondaryContainer.toArgb(),
            onSecondaryContainer = onSecondaryContainer.toArgb(),
            tertiary = tertiary.toArgb(),
            onTertiary = onTertiary.toArgb(),
            tertiaryContainer = tertiaryContainer.toArgb(),
            onTertiaryContainer = onTertiaryContainer.toArgb(),
            background = background.toArgb(),
            onBackground = onBackground.toArgb(),
            surface = surface.toArgb(),
            onSurface = onSurface.toArgb(),
            surfaceVariant = surfaceVariant.toArgb(),
            onSurfaceVariant = onSurfaceVariant.toArgb(),
            surfaceTint = surfaceTint.toArgb(),
            inverseSurface = inverseSurface.toArgb(),
            inverseOnSurface = inverseOnSurface.toArgb(),
            error = error.toArgb(),
            onError = onError.toArgb(),
            errorContainer = errorContainer.toArgb(),
            onErrorContainer = onErrorContainer.toArgb(),
            outline = outline.toArgb(),
            outlineVariant = outlineVariant.toArgb(),
            scrim = scrim.toArgb(),
            surfaceBright = surfaceBright.toArgb(),
            surfaceContainer = surfaceContainer.toArgb(),
            surfaceContainerHigh = surfaceContainerHigh.toArgb(),
            surfaceContainerHighest = surfaceContainerHighest.toArgb(),
            surfaceContainerLow = surfaceContainerLow.toArgb(),
            surfaceContainerLowest = surfaceContainerLowest.toArgb(),
            surfaceDim = surfaceDim.toArgb(),
        )

